In [3]:
import pandas as pd
import numpy as np

print("pandas version :", pd.__version__)
print("numpy version :", np.__version__)

pandas version : 3.0.6
numpy version : 2.4.6

In [4]:
# On remonte d'un dossier (..) pour aller dans data/brut/
chemin = "../data/brut/rendez_vous_medirdv_brut.csv"

# Chargement du fichier
df = pd.read_csv(chemin, encoding="utf-8", sep=",")

print("Dimensions du fichier :", df.shape)
print("\nColonnes :", df.columns.tolist())

# Afficher les 5 premières lignes
df.head()

Dimensions du fichier : (2040, 20)

Colonnes : ['id_rdv', 'date_prise', 'date_rdv', 'heure_rdv', 'duree_min', 'specialite', 'medecin_id', 'medecin_nom', 'patient_id', 'patient_nom', 'patient_prenom', 'sexe', 'date_naissance', 'telephone', 'quartier', 'canal', 'confirme', 'statut', 'motif_annulation', 'agent_saisie']

,id_rdv,date_prise,date_rdv,heure_rdv,duree_min,specialite,medecin_id,medecin_nom,patient_id,patient_nom,patient_prenom,sexe,date_naissance,telephone,quartier,canal,confirme,statut,motif_annulation,agent_saisie
0,RDV01965,2026-12-12,2026-12-24,16:00,30,Gynécologie-obstétrique,MED014,Dr Aliou Ndiaye,PAT00480,Gomis,Aminata,F,1991-09-28,789443078,Liberté,Guichet,Non,Planifié,NaN,AGT07
1,RDV00432,2025-12-30,2026-01-03,10:20,20,Ophtalmologie,MED020,Dr Adama Badji,PAT00333,Camara,Modou,M,2013-10-22,769265045,Plateau,Guichet,Non,Honoré,NaN,AGT03
2,RDV00708,2026-03-03,2026-03-09,17:15,15,Médecine générale,MED003,Dr Seynabou Dia,PAT00975,Badji,Binta,F,1952-09-11,787271829,Médina,NaN,Non,Honoré,NaN,AGT01
3,RDV00331,2025-12-15,2025-12-15,09:00,30,Cardiologie,MED017,Dr Oumou Seck,PAT00593,Mbaye,Aliou,M,2021-06-23,704789138,Rufisque,Téléphone,Oui,Honoré,NaN,AGT07
4,RDV00340,2025-12-15,2025-12-16,10:20,20,Pédiatrie,MED009,Dr Youssou Fall,PAT00573,Sow,Souleymane,M,2011-09-10,757078011,Liberté,Téléphone,Oui,Honoré,NaN,AGT04

In [5]:
# 1. Valeurs manquantes par colonne
print("--- VALEURS MANQUANTES ---")
print(df.isna().sum().sort_values(ascending=False))

# 2. Doublons complets (lignes identiques)
print("\n--- DOUBLONS COMPLETS ---")
print("Nombre de lignes dupliquées :", df.duplicated().sum())

# 3. Doublons sur l'identifiant unique id_rdv
print("\n--- DOUBLONS ID_RDV ---")
print("Nombre d'id_rdv dupliqués :", df["id_rdv"].duplicated().sum())

--- VALEURS MANQUANTES ---
motif_annulation    1899
quartier              45
telephone             35
confirme              30
date_naissance        25
canal                 20
date_prise             0
id_rdv                 0
heure_rdv              0
date_rdv               0
duree_min              0
specialite             0
sexe                   0
patient_prenom         0
patient_nom            0
patient_id             0
medecin_nom            0
medecin_id             0
statut                 0
agent_saisie           0
dtype: int64

--- DOUBLONS COMPLETS ---
Nombre de lignes dupliquées : 25

--- DOUBLONS ID_RDV ---
Nombre d'id_rdv dupliqués : 25

In [6]:
# Regardons les valeurs uniques pour les colonnes catégorielles
for col in ["specialite", "sexe", "statut", "canal", "confirme", "motif_annulation"]:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False))

--- specialite ---
specialite
Médecine générale          536
Pédiatrie                  291
Gynécologie-obstétrique    289
Cardiologie                178
Endocrinologie             163
Ophtalmologie              150
Dermatologie               146
ORL                        106
Kinésithérapie              96
cardiologie                 11
Medecine generale           11
Gynecologie                 10
MG                           8
endocrino                    7
PEDIATRIE                    7
pediatrie                    5
Gynéco                       5
Ophtalmo                     4
Dermato                      4
médecine générale            4
Pédiatrie                    4
O.R.L                        3
Kiné                         1
kinesitherapie               1
Name: count, dtype: int64

--- sexe ---
sexe
F        1257
M         743
F          11
Femme      10
f           9
H           5
m           4
Homme       1
Name: count, dtype: int64

--- statut ---
statut
Honoré      1239
Planifié     233
Absent       201
Confirmé     162
Annulé       153
OK            19
honore        13
Venu           8
HONORÉ         7
No-show        2
Non venu       1
absent         1
ABSENT         1
Name: count, dtype: int64

--- canal ---
canal
Téléphone                 819
Guichet                   793
Recommandation médecin    408
NaN                        20
Name: count, dtype: int64

--- confirme ---
confirme
Oui    1056
Non     954
NaN      30
Name: count, dtype: int64

--- motif_annulation ---
motif_annulation
NaN         1899
Patient       77
Médecin       34
Clinique      18
Autre         12
Name: count, dtype: int64

In [7]:
# 4. Regardons les valeurs uniques pour les colonnes catégorielles
for col in ["specialite", "sexe", "statut", "canal", "confirme", "motif_annulation"]:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False))

--- specialite ---
specialite
Médecine générale          536
Pédiatrie                  291
Gynécologie-obstétrique    289
Cardiologie                178
Endocrinologie             163
Ophtalmologie              150
Dermatologie               146
ORL                        106
Kinésithérapie              96
cardiologie                 11
Medecine generale           11
Gynecologie                 10
MG                           8
endocrino                    7
PEDIATRIE                    7
pediatrie                    5
Gynéco                       5
Ophtalmo                     4
Dermato                      4
médecine générale            4
Pédiatrie                    4
O.R.L                        3
Kiné                         1
kinesitherapie               1
Name: count, dtype: int64

--- sexe ---
sexe
F        1257
M         743
F          11
Femme      10
f           9
H           5
m           4
Homme       1
Name: count, dtype: int64

--- statut ---
statut
Honoré      1239
Planifié     233
Absent       201
Confirmé     162
Annulé       153
OK            19
honore        13
Venu           8
HONORÉ         7
No-show        2
Non venu       1
absent         1
ABSENT         1
Name: count, dtype: int64

--- canal ---
canal
Téléphone                 819
Guichet                   793
Recommandation médecin    408
NaN                        20
Name: count, dtype: int64

--- confirme ---
confirme
Oui    1056
Non     954
NaN      30
Name: count, dtype: int64

--- motif_annulation ---
motif_annulation
NaN         1899
Patient       77
Médecin       34
Clinique      18
Autre         12
Name: count, dtype: int64

In [8]:
for col in ["sexe", "statut", "canal", "confirme"]:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False))

--- sexe ---
sexe
F        1257
M         743
F          11
Femme      10
f           9
H           5
m           4
Homme       1
Name: count, dtype: int64

--- statut ---
statut
Honoré      1239
Planifié     233
Absent       201
Confirmé     162
Annulé       153
OK            19
honore        13
Venu           8
HONORÉ         7
No-show        2
Non venu       1
absent         1
ABSENT         1
Name: count, dtype: int64

--- canal ---
canal
Téléphone                 819
Guichet                   793
Recommandation médecin    408
NaN                        20
Name: count, dtype: int64

--- confirme ---
confirme
Oui    1056
Non     954
NaN      30
Name: count, dtype: int64

In [9]:
# Conversion des dates
df["date_prise_parsee"] = pd.to_datetime(df["date_prise"], errors="coerce", dayfirst=False)
df["date_rdv_parsee"]   = pd.to_datetime(df["date_rdv"],   errors="coerce", dayfirst=False)

print("date_prise non parsées :", df["date_prise_parsee"].isna().sum())
print("date_rdv non parsées   :", df["date_rdv_parsee"].isna().sum())

# RDV avant la prise
masque = df["date_rdv_parsee"] < df["date_prise_parsee"]
print("\nRDV avant la date de prise :", masque.sum())
df[masque][["id_rdv", "date_prise", "date_rdv"]].head(10)

date_prise non parsées : 0
date_rdv non parsées   : 71

RDV avant la date de prise : 15

        id_rdv  date_prise    date_rdv
89    RDV01051  2026-06-17  2026-06-08
227   RDV01845  2026-12-10  2026-11-24
316   RDV01674  2026-10-21  2026-10-15
364   RDV01959  2027-01-01  2026-12-22
404   RDV01498  2026-09-20  2026-09-10
464   RDV01042  2026-06-15  2026-06-05
1051  RDV00106  2025-11-05  2025-10-23
1138  RDV00328  2025-12-20  2025-12-15
1368  RDV01080  2026-07-03  2026-06-17
1376  RDV00935  2026-05-18  2026-05-09

In [10]:
print("Durées distinctes :", sorted(df["duree_min"].dropna().unique()))
print("\nHeures distinctes (échantillon) :")
print(df["heure_rdv"].dropna().unique()[:30])

Durées distinctes : [np.int64(-15), np.int64(0), np.int64(1), np.int64(15), np.int64(20), np.int64(30), np.int64(300)]

Heures distinctes (échantillon) :
<StringArray>
['16:00', '10:20', '17:15', '09:00', '10:00', '14:20', '08:30', '11:30',
 '15:00', '10:30', '08:40', '11:00', '16:30', '14:00', '09:30', '09:45',
 '09:20', '14:45', '17:00', '15:30', '08:20', '11:15', '17:20', '10:40',
 '16:40', '16:45', '08:00', '16:20', '08:45', '11:40']
Length: 30, dtype: str

In [11]:
# Identifier les id_rdv dupliqués
ids_dupliques = df[df.duplicated(subset="id_rdv", keep=False)].sort_values("id_rdv")
print("Lignes concernées :", len(ids_dupliques))
print("Id_rdv uniques concernés :", ids_dupliques["id_rdv"].nunique())
print("\nExemples :")
display(ids_dupliques[["id_rdv", "date_prise", "date_rdv", "patient_id", "statut"]].head(10))

# Vérifier que chaque id_rdv dupliqué est bien une ligne strictement identique
doublons_exacts = df[df.duplicated(keep=False)]
print("\nLignes strictement identiques :", len(doublons_exacts))

Lignes concernées : 50
Id_rdv uniques concernés : 25

Exemples :

        id_rdv  date_prise    date_rdv patient_id  statut
1720  RDV00079  2025-10-08  2025-10-16   PAT00059  Annulé
1539  RDV00079  2025-10-08  2025-10-16   PAT00059  Annulé
1177  RDV00203  2025-11-16  2025-11-17   PAT00030  Honoré
1432  RDV00203  2025-11-16  2025-11-17   PAT00030  Honoré
1921  RDV00310  2025-11-24  2025-12-11   PAT00629  Honoré
1119  RDV00310  2025-11-24  2025-12-11   PAT00629  Honoré
434   RDV00390  2025-12-24  2025-12-26   PAT00783  Honoré
1207  RDV00390  2025-12-24  2025-12-26   PAT00783  Honoré
369   RDV00442  2025-12-26  2026-01-06   PAT00871  Honoré
1977  RDV00442  2025-12-26  2026-01-06   PAT00871  Honoré

Lignes strictement identiques : 50

In [12]:
df = df.drop_duplicates().reset_index(drop=True)
print("Dimensions après suppression :", df.shape)

Dimensions après suppression : (2015, 22)

In [13]:
df["date_prise_parsee"] = pd.to_datetime(df["date_prise"], errors="coerce", dayfirst=False)
df["date_rdv_parsee"]   = pd.to_datetime(df["date_rdv"],   errors="coerce", dayfirst=False)

# Délai en jours
df["delai_jours"] = (df["date_rdv_parsee"] - df["date_prise_parsee"]).dt.days

print("RDV pris après la date du RDV (délai < 0) :", (df["delai_jours"] < 0).sum())
print("RDV à plus de 90 jours :", (df["delai_jours"] > 90).sum())
print("\nDélai min :", df["delai_jours"].min())
print("Délai max :", df["delai_jours"].max())
print("Délai moyen :", round(df["delai_jours"].mean(), 1))

RDV pris après la date du RDV (délai < 0) : 15
RDV à plus de 90 jours : 0

Délai min : -18.0
Délai max : 66.0
Délai moyen : 8.3

In [14]:
print(df["canal"].value_counts(dropna=False))

canal
Téléphone                 807
Guichet                   786
Recommandation médecin    402
NaN                        20
Name: count, dtype: int64

In [15]:
# Trouver les dates au format JJ/MM/AAAA
masque = df["date_rdv"].astype(str).str.contains("/", na=False)
print("Dates au format JJ/MM/AAAA :", masque.sum())
print("\nExemples :")
print(df[masque][["id_rdv", "date_prise", "date_rdv"]].head(10))

Dates au format JJ/MM/AAAA : 71

Exemples :
       id_rdv  date_prise    date_rdv
42   RDV01951  2026-12-11  19/12/2026
85   RDV00612  2026-02-04  12/02/2026
87   RDV00572  2026-02-03  05/02/2026
114  RDV00201  2025-10-26  17/11/2025
131  RDV00431  2025-12-16  03/01/2026
136  RDV00413  2025-12-30  30/12/2025
153  RDV01814  2026-11-10  17/11/2026
188  RDV01997  2026-12-19  31/12/2026
242  RDV00354  2025-12-17  19/12/2025
251  RDV00528  2026-01-18  26/01/2026

In [16]:
def parser_date(val):
    if pd.isna(val):
        return pd.NaT
    val = str(val).strip()
    for fmt in ("%Y-%m-%d", "%d/%m/%Y"):
        try:
            return pd.to_datetime(val, format=fmt)
        except ValueError:
            continue
    return pd.NaT

df["date_prise_parsee"] = df["date_prise"].apply(parser_date)
df["date_rdv_parsee"]   = df["date_rdv"].apply(parser_date)

print("date_prise non parsées :", df["date_prise_parsee"].isna().sum())
print("date_rdv non parsées   :", df["date_rdv_parsee"].isna().sum())

# Recalcul du délai
df["delai_jours"] = (df["date_rdv_parsee"] - df["date_prise_parsee"]).dt.days

print("\n--- RG-04 : Délai de prise ---")
print("RDV avant la date de prise :", (df["delai_jours"] < 0).sum())
print("RDV à plus de 90 jours     :", (df["delai_jours"] > 90).sum())
print("Délai min :", df["delai_jours"].min())
print("Délai max :", df["delai_jours"].max())
print("Délai moyen :", round(df["delai_jours"].mean(), 1))

date_prise non parsées : 0
date_rdv non parsées   : 0

--- RG-04 : Délai de prise ---
RDV avant la date de prise : 15
RDV à plus de 90 jours     : 0
Délai min : -18
Délai max : 66
Délai moyen : 8.3

In [17]:
# Doublons d'id_rdv
ids_dupliques = df[df.duplicated(subset="id_rdv", keep=False)].sort_values("id_rdv")
print("Lignes concernées :", len(ids_dupliques))
print("Id_rdv uniques concernés :", ids_dupliques["id_rdv"].nunique())

# Doublons strictement identiques (toutes les colonnes)
doublons_exacts = df[df.duplicated(keep=False)]
print("\nLignes strictement identiques :", len(doublons_exacts))

Lignes concernées : 0
Id_rdv uniques concernés : 0

Lignes strictement identiques : 0